services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: global-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      # Web
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro
    networks:
      - sr-reverse-proxy

  mariadb:
    image: mariadb:10.6
    container_name: global-mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/mysql/config.cnf:/etc/mysql/mysql.conf.d/wp-local-docker.cnf:ro
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      sr-reverse-proxy:
      sr-public_network:
        ipv4_address: 10.0.120.10

  phpmyadmin:
    image: phpmyadmin
    container_name: global-phpmyadmin
    ports:
      - 8092:80
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    networks:
      - sr-public_network
      - sr-reverse-proxy

networks:
  sr-reverse-proxy:
    external: true
  sr-public_network:
    external: true

volumes:
  mysql_data:


# comando mkcert
# mkcert -cert-file certs/localhost-cert.pem -key-file certs/localhost-key.pem "*.docker.localhost" "*.local" "*.test"

